# Generated by Django 4.0.1 on 2022-01-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='', verbose_name='Текст'),
            preserve_default=False,
        ),
    ]
